server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BlackAndWhile/springcloud.git
          searchPaths: config
          username: 2662067212@qq.com
          password: lzqa2703
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


